.TH BSP-MASTERSTACK 1 bsp-masterstack\-{{VERSION}}
.SH NAME
bsp-masterstack \- Add master stack to bspwm

.SH SYNOPSIS
.B bsp-masterstack
.RB [start|stop|zoom|replay|version|help]

.SH DESCRIPTION

.SH OPTIONS

.SH LAYOUTS

.SH BUGS
Report issues to https://github.com/abeldekat/bsp-masterstack/issues

.SH AUTHOR
Abel Dekat <bsp-masterstack@tweeberen.xyz>

.SH LINKS
Homepage <https://github.com/abeldekat/bsp-masterstack>
Inspiration <https://github.com/phenax/bsp-layout>
