#!/usr/bin/env bash
source "$ROOT/utils/state.sh";
source "$ROOT/utils/desktop.sh";
source "$ROOT/adapters/alternate.sh";

# Gatekeeper: Only handle event if:
# Event target desktop is a match, or event is not from bspwm
# In case event is node_transfer: Event src desktop is not a match
_should_handle_event(){
    if [[ $1 == "zoom" ]]; then
        echo true;
        return;
    fi

    local result=false;
    local desktop_id="";
    if [[ "$1" == "node_transfer" ]]; then
        [[ "$3" != "$6" ]] && desktop_id="$6";
    else
        desktop_id="$3";
    fi;

    if [[ -n "$desktop_id" ]]; then
        local desktop_name_event=$(get_desktop_name_from_id "$desktop_id");
        [[ "$desktop_name_event" == "$DESKTOPNAME" ]] && result=true;
    fi;
    echo $result;
}

# Pass event to the correct method
_handle_event(){
    cmd=$1; shift;
    case "$cmd" in
      node_add) node_add "$@" ;;
      node_remove) node_remove ;;
      node_transfer) node_transfer "$@" ;;
      zoom) zoom ;;
      *) ;;
    esac;
}

# All events of interest
# 1. Bspwm events
# 2. Events generated by this project via a named pipe
_capture_events(){
    bspc subscribe node_add node_remove node_transfer &
    while :; do
        if read message <$THIS_DESKTOP_FIFO; then
            [[ "$message" == 'quit' ]] && break;
            echo $message;
        fi
    done &
}

# Acitvates listener for a specific desktop
# Reads both bspwm events and commands issued by this project through a fifo
# The fifo needs to be closed and removed on exit
_start() {
    {
        trap "echo quit > $THIS_DESKTOP_FIFO && rm $THIS_DESKTOP_FIFO" EXIT;
        while read -r -a line; do
            if "$(_should_handle_event ${line[@]})"; then
                _handle_event ${line[@]};
            fi;
        done < <(_capture_events)
    } &
    local ADAPTER_PID=$!;
    disown;
    set_desktop_option $DESKTOPNAME 'pid' "$ADAPTER_PID";
    echo "[$ADAPTER_PID]";
}

# Masterstack variables
DESKTOPNAME="$1";
DESKTOP="@$DESKTOPNAME:";
_master="1";
MASTER="$DESKTOP/$_master";
_stack="2";
STACK="$DESKTOP/$_stack";
NEW_NODE="1";
# For example: @I:/1/1/
MASTER_NEWNODE="$MASTER/$NEW_NODE";
# For example: @I:/2/1/
STACK_TOP="$STACK/$NEW_NODE";

# Start the listener
# echo "Starting listener for desktop $DESKTOPNAME";
THIS_DESKTOP_FIFO="$(get_desktop_fifo $DESKTOPNAME)";
if [[ ! -p $THIS_DESKTOP_FIFO ]]; then
    mkfifo $THIS_DESKTOP_FIFO;
fi
_start;
